jenkins:
  systemMessage: "Internal CI/CD Platform - Managed by Configuration as Code"

  numExecutors: ${JENKINS_NUM_EXECUTORS:-4}
  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_USER}"
          password: "${JENKINS_ADMIN_PASSWORD}"
          name: "Admin User"

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_ADMIN_USER}"
        - "Overall/Read:authenticated"
        - "Job/Build:authenticated"
        - "Job/Cancel:authenticated"
        - "Job/Read:authenticated"
        - "Job/Workspace:authenticated"
        - "View/Read:authenticated"

  remotingSecurity:
    enabled: true

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

# Credentials configuration
credentials:
  system:
    domainCredentials:
      - credentials:
          # SonarQube token (optional - configure via UI)
          - string:
              scope: GLOBAL
              id: "sonarqube-token"
              secret: "${SONAR_TOKEN:-changeme}"
              description: "SonarQube authentication token"

# Tool installations
tool:
  git:
    installations:
      - name: "Default"
        home: "git"

# SonarQube configuration
unclassified:
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
      - name: "Internal SonarQube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonarqube-token"

  location:
    url: "http://${JENKINS_DOMAIN:-localhost:8080}/"
    adminAddress: "cicd@company.com"

# Job DSL seed configuration
jobs:
  - script: >
      folder('Shared-Pipelines') {
        displayName('Shared Pipeline Templates')
        description('Reusable pipeline templates for different tech stacks')
      }

      folder('Team-Projects') {
        displayName('Team Projects')
        description('Folder for team-specific projects')
      }

      folder('Infrastructure') {
        displayName('Infrastructure Jobs')
        description('Infrastructure and maintenance jobs')
      }
